INSERT INTO MOM_QSTN(MOM_USR_ID, MOM_CATG_ID, QUESTION, DESCRIPTION)
VALUES
(777777, 2, 'WHO IS THE FOUNDER OF MOMBURBIA WHO IS TNDER OF MOMBURBIA WHO IS THE FOUNDER OF MOMBURBIA', 'JUST CHECKING WHAT IS THE BEST THINGS')