ALTER TRIGGER TR_MOM_GRP_USR_ADD
ON	MOM_GRP_USR
AFTER	INSERT
AS
	UPDATE	MOM_GRP
	SET	MEMBERS = ISNULL (MEMBERS, 0) + 1
	WHERE	ID = (SELECT MOM_GRP_ID FROM INSERTED)
GO

CREATE TRIGGER TR_MOM_MOM_ANWS_ADD
ON	MOM_ANWS
AFTER	INSERT
AS
	UPDATE	MOM_QSTN
	SET	ANSWERS_COUNT = ISNULL (ANSWERS_COUNT, 0) + 1
	WHERE	ID = (SELECT MOM_QSTN_ID FROM INSERTED)
GO
