--DROP TRIGGER TR_MOM_GRP_USR_ADD
ALTER TRIGGER TR_MOM_GRP_USR_ADD
ON	MOM_FRND
AFTER	INSERT
AS
	UPDATE	MOM_GRP
	SET	MEMBERS = ISNULL (MEMBERS, 0) + 1
	WHERE	ID = (SELECT MG.ID FROM INSERTED I INNER JOIN MOM_GRP MG ON I.MOM_USR_ID = MG.GRP_MOM_USR_ID)
GO

CREATE TRIGGER TR_MOM_MOM_ANWS_ADD
ON	MOM_ANWS
AFTER	INSERT
AS
	UPDATE	MOM_QSTN
	SET	ANSWERS_COUNT = ISNULL (ANSWERS_COUNT, 0) + 1
	WHERE	ID = (SELECT MOM_QSTN_ID FROM INSERTED)
GO


CREATE TRIGGER TR_MOM_MOM_ALBM_PHTO_ADD
ON	MOM_ALBM_PHTO
AFTER	INSERT
AS
	UPDATE	MOM_ALBM
	SET	PHOTOS = ISNULL (PHOTOS, 0) + 1
	WHERE	ID = (SELECT MOM_ALBM_ID FROM INSERTED)
GO