IF OBJECT_ID('MOM_MAIL') IS NOT NULL
	DROP TABLE MOM_MAIL
	
CREATE TABLE MOM_MAIL
(
	  ID			INT				NOT NULL	IDENTITY(1,1)
	, MOM_USR_ID	BIGINT			NOT NULL
	, MOM_TO_EMAIL	VARCHAR(255)	NULL
	, MOM_SUBJECT	VARCHAR(100)	NULL	
	, MOM_BODY		TEXT			NULL	
	, MOM_READ		BIT				NULL	DEFAULT ((0))
	, TIME			DATETIME		NOT NULL	DEFAULT (GETDATE())
)