IF OBJECT_ID('MOM_FRG_CMNT') IS NOT NULL
	DROP TABLE MOM_FRG_CMNT

CREATE TABLE MOM_FRG_CMNT
(
	  ID		INT IDENTITY (1, 1)
	, MOM_FRG_ID	INT
	, MOM_USR_ID	BIGINT
	, COMMENTS	NVARCHAR (255)
	, TIME		DATETIME DEFAULT (GETDATE())
)