IF OBJECT_ID('MOM_FAV_RCP') IS NOT NULL
	DROP TABLE MOM_FAV_RCP


CREATE TABLE MOM_FAV_RCP(
	  ID		INT		NOT NULL	IDENTITY(1,1)
	, MOM_RCP_ID	INT		NOT NULL
	, MOM_USR_ID	BIGINT		NOT NULL
	, TIME		DATETIME	NOT NULL	DEFAULT (GETDATE())
) 