IF OBJECT_ID('MOM_QSTN') IS NOT NULL
	DROP TABLE MOM_QSTN

CREATE TABLE MOM_QSTN
(
	  ID		INT IDENTITY (1,1)
	, MOM_USR_ID	BIGINT
	, MOM_CATG_ID	INT
	, QUESTION	NVARCHAR (100)
	, DESCRIPTION	NVARCHAR (2000)
	, EMAIL_STATUS	BIT
	, STATUS		BIT DEFAULT (1)
	, TIME		DATETIME	DEFAULT (GETDATE())
	, ABUSE		BIT DEFAULT(0)	
)