IF OBJECT_ID('MOM_RCP_VIEW') IS NOT NULL
	DROP TABLE MOM_RCP_VIEW

CREATE TABLE MOM_RCP_VIEW(
	  ID		INT		NOT NULL	IDENTITY(1,1)
	, MOM_RCP_ID	INT		NOT NULL
	, MOM_USR_ID	BIGINT		NOT NULL
	, TIME		DATETIME	NOT NULL	DEFAULT (GETDATE())
)