IF OBJECT_ID('MOM_RCP') IS NOT NULL
	DROP TABLE MOM_RCP

CREATE TABLE MOM_RCP(
	  ID		INT		NOT NULL	IDENTITY(1,1)
	, NAME		VARCHAR(100)	NOT NULL
	, DESCRIPTION	VARCHAR(255)	NULL
	, PHOTO		VARCHAR(255)	NULL
	, TAGS		VARCHAR(255)	NULL
	, PREP_TM	VARCHAR(100)	NULL
	, COOK_TM	VARCHAR(100)	NULL
	, SERVE_TO	VARCHAR(100)	NULL
	, DIFFICULTY	VARCHAR(100)	NOT NULL
	, INGREDIENTS	TEXT		NOT NULL
	, METHOD	TEXT		NOT NULL
	, VEGE		BIT		NULL
	, VEGAN		BIT		NULL
	, DAIRY		BIT		NULL
	, GLUTEN	BIT		NULL
	, NUT		BIT		NULL
	, ALLOW		BIT		NULL
	, MOM_USR_ID	BIGINT		NULL
	, TIME		DATETIME	NOT NULL	DEFAULT (GETDATE())
) 