IF OBJECT_ID('MOM_FRND') IS NOT NULL
	DROP TABLE MOM_FRND

CREATE TABLE MOM_FRND
(
	  ID		BIGINT IDENTITY (1,1)
	, MOM_USR_ID	BIGINT
	, FRND_MOM_USR_ID	BIGINT
	, TIME		DATETIME
	, BLOCKED	BIT
	, BLOCKED_TIME	DATETIME
)