IF OBJECT_ID('MOM_USR_EDU') IS NOT NULL
	DROP TABLE MOM_USR_EDU

CREATE TABLE MOM_USR_EDU(
	  ID				INT				NOT NULL	IDENTITY(1,1)
	, MOM_SCH_NAME		VARCHAR(50)		NOT NULL
	, MOM_SCH_TYPE		VARCHAR(20)		NULL
	, MOM_SCH_ST		INT				NULL
	, MOM_SCH_ED		INT				NULL
	, MOM_USR_ID		BIGINT			NULL
	, TIME				DATETIME		NOT NULL	DEFAULT (GETDATE())
)