IF OBJECT_ID('MOM_USR_PRIVACY') IS NOT NULL
	DROP TABLE MOM_USR_PRIVACY

CREATE TABLE MOM_USR_PRIVACY(
	  MOM_USR_ID			BIGINT			NOT NULL
	, MOM_SHW_NAME			NVARCHAR(20)	NULL
	, MOM_SHW_DOB			NVARCHAR(20)	NULL
	, MOM_SHW_INTRST		NVARCHAR(20)	NULL
	, MOM_SHW_EDU			NVARCHAR(20)	NULL
	, MOM_SHW_KIDS			NVARCHAR(20)	NULL
	, MOM_SHW_KIDS_DOB		NVARCHAR(20)	NULL
	, MOM_SHW_KIDS_PHOTO	NVARCHAR(20)	NULL
	, MOM_SHW_KIDS_ABOUT	NVARCHAR(20)	NULL
	, MOM_SHW_KIDS_CHAN		NVARCHAR(20)	NULL
	, MOM_SHW_ACT			NVARCHAR(20)	NULL
	, MOM_SHW_TO			NVARCHAR(20)	NULL
	, TIME					DATETIME		NOT NULL	DEFAULT (GETDATE())
)