IF OBJECT_ID('MOM_ANWS') IS NOT NULL
	DROP TABLE MOM_ANWS

CREATE TABLE MOM_ANWS
(
	  ID		INT IDENTITY (1,1)
	, MOM_USR_ID	BIGINT
	, MOM_QSTN_ID	INT
	, ANSWER		NVARCHAR (1000)
	, TIME		DATETIME DEFAULT (GETDATE())
	, ABUSE		BIT DEFAULT (0)
)