IF OBJECT_ID('MOM_FRG') IS NOT NULL
	DROP TABLE MOM_FRG

CREATE TABLE MOM_FRG
(
	  ID		INT IDENTITY (1, 1)
	, MOM_USR_ID	BIGINT
	, SHARE		NVARCHAR (255)
	, TIME		DATETIME DEFAULT (GETDATE())
)

