IF OBJECT_ID('MOM_BLG') IS NOT NULL
	DROP TABLE MOM_BLG

CREATE TABLE MOM_BLG
(
	  ID		INT IDENTITY (1,1)
	, MOM_USR_ID	BIGINT
	, BLOG		NVARCHAR (4000)
	, STATUS		BIT
	, TIME		DATETIME
	, ABUSE		BIT
	, APPROVED	BIT
	, VIEWS		INT
	, RATE		SMALLINT
)