IF OBJECT_ID('MOM_RCP_RT') IS NOT NULL
	DROP TABLE MOM_RCP_RT

CREATE TABLE MOM_RCP_RT(
	  ID		INT		NOT NULL	IDENTITY(1,1)
	, MOM_RCP_ID	INT		NOT NULL
	, MOM_USR_ID	BIGINT		NOT NULL
	, RATE		INT		NOT NULL
	, TIME		DATETIME	NOT NULL	DEFAULT (GETDATE())
) 