IF OBJECT_ID('MOM_IP_TRK') IS NOT NULL
	DROP TABLE MOM_IP_TRK

CREATE TABLE MOM_IP_TRK
(
	  ID		INT IDENTITY (1, 1)
	, IP_ADR		NVARCHAR (20)
	, SYS_USR	NVARCHAR (100)
	, MOM_USR_ID	BIGINT
	, TIME		DATETIME DEFAULT (GETDATE())
)