IF OBJECT_ID('MOM_USR_FAV') IS NOT NULL
	DROP TABLE MOM_USR_FAV

CREATE TABLE MOM_USR_FAV(
	  MOM_USR_ID		BIGINT
	, MOM_FAV_CELEB		TEXT		NULL
	, MOM_FAV_MOV		TEXT		NULL
	, MOM_FAV_TV		TEXT		NULL
	, MOM_FAV_BOOKS		TEXT		NULL
	, MOM_FAV_MUSIC		TEXT		NULL
	, TIME				DATETIME	NOT NULL	DEFAULT (GETDATE())
)