ALTER PROC MOM_QSTN_ADD
(
	  @MOM_USR_ID	BIGINT
	, @MOM_CATG_ID	INT
	, @QUESTION	NVARCHAR (100)
	, @DESCRIPTION	NVARCHAR (2000)
	, @EMAIL_STATUS	BIT
)
AS
BEGIN TRAN

	INSERT INTO MOM_QSTN
	(
		  MOM_USR_ID
		, MOM_CATG_ID
		, QUESTION
		, DESCRIPTION
		, EMAIL_STATUS
	)
	VALUES
	(
		  @MOM_USR_ID
		, @MOM_CATG_ID
		, @QUESTION
		, @DESCRIPTION
		, @EMAIL_STATUS
	)

COMMIT TRAN