/*
ADDS ROW TO MOM_USR TABLE
*/

ALTER PROC SP_MOM_USR_ADD
(
	  @EMAIL_ADDR	NVARCHAR (200)
	, @PASSWORD	NVARCHAR (100)
	, @FIRST_NAME	NVARCHAR (100)
	, @LAST_NAME	NVARCHAR (100)
	, @SEX		NCHAR (1)
	, @DOB		DATETIME
	, @DISPLAY_NAME	NVARCHAR (30)
	, @NEWLETTER	BIT
	, @ID		BIGINT OUT
)
AS
BEGIN TRAN
	INSERT INTO MOM_USR
	(
		  EMAIL_ADDR
		, PASSWORD
		, FIRST_NAME
		, LAST_NAME
		, SEX
		, DOB
		, DISPLAY_NAME
		, FULL_NAME
		, NEWLETTER
	)
	VALUES
	(
		  @EMAIL_ADDR
		, @PASSWORD
		, @FIRST_NAME
		, @LAST_NAME
		, @SEX
		, @DOB
		, @DISPLAY_NAME
		, @FIRST_NAME + ' ' + @LAST_NAME
		, @NEWLETTER
	)
	SET @ID = @@IDENTITY
COMMIT TRAN