set ANSI_NULLS ON
set QUOTED_IDENTIFIER ON
go

ALTER PROC [dbo].[SP_GET_MOM_USR_PRIVACY]
(
	@MOM_USR_ID	INT
)
AS
BEGIN
	
	SET TRAN ISOLATION LEVEL READ UNCOMMITTED
	SET NOCOUNT ON
	SELECT    MOM_USR_ID
			, MOM_SHW_NAME
			, MOM_SHW_DOB
			, MOM_SHW_INTRST
			, MOM_SHW_EDU
			, MOM_SHW_KIDS
			, MOM_SHW_KIDS_DOB
			, MOM_SHW_KIDS_PHOTO
			, MOM_SHW_KIDS_ABOUT
			, MOM_SHW_KIDS_CHAN
			, MOM_SHW_ACT
			, MOM_SHW_TO
	FROM MOM_USR_PRIVACY
	WHERE MOM_USR_ID = @MOM_USR_ID
END


