set ANSI_NULLS ON
set QUOTED_IDENTIFIER ON
go

ALTER PROC [dbo].[SP_GET_MOM_USR_FAV]
(
	@MOM_USR_ID	INT
)
AS
BEGIN
	
	SET TRAN ISOLATION LEVEL READ UNCOMMITTED
	SET NOCOUNT ON
	SELECT    MOM_USR_ID
			, MOM_FAV_CELEB
			, MOM_FAV_MOV
			, MOM_FAV_TV
			, MOM_FAV_BOOKS
			, MOM_FAV_MUSIC
	FROM MOM_USR_FAV
	WHERE MOM_USR_ID = @MOM_USR_ID
END


