ALTER PROC SP_MOM_FRG_GET_BY_MOM_USR_ID
(
	  @MOM_USR_ID	BIGINT
	, @TYPE	CHAR (1)	= NULL
)
AS
	SET TRAN ISOLATION LEVEL READ UNCOMMITTED
	SET NOCOUNT ON

	SELECT	FRND_MOM_USR_ID
	INTO	#MOM_FRND_TEMP
	FROM	MOM_FRND (NOLOCK)
	WHERE	MOM_USR_ID = @MOM_USR_ID
	AND	BLOCKED = 0
	
	UNION
	
	SELECT	MOM_USR_ID
	FROM	MOM_FRND (NOLOCK)
	WHERE	FRND_MOM_USR_ID = @MOM_USR_ID
	AND	BLOCKED = 0
	
	UNION
	
	SELECT	@MOM_USR_ID
	

	SELECT	  MF.ID
		, MF.MOM_USR_ID
		, MF.SHARE
		, TIME	= DBO.FN_MOM_DATE_DIFF(MF.TIME, GETDATE())
		, MU.DISPLAY_NAME
		, PICTURE	= ISNULL (MU.PICTURE, '../images/q_silhouette.gif')
		, MF.TYPE
		, MF.TYPE_SHARE
		, MF.HIDE
	INTO	#MOM_FRG
	FROM	#MOM_FRND_TEMP MFT (NOLOCK)
		INNER JOIN MOM_USR MU (NOLOCK)
		ON	MFT.FRND_MOM_USR_ID = MU.ID
		INNER JOIN MOM_FRG MF (NOLOCK)
		ON	MU.ID = MF.MOM_USR_ID
	WHERE	HIDE = 0
	AND	(MF.TYPE = @TYPE OR @TYPE IS NULL)
	ORDER BY MF.ID DESC
	
	SELECT	*
	FROM	#MOM_FRG
	
	SELECT	  MFC.ID
		, MFC.MOM_FRG_ID
		, MFC.COMMENTS
		, TIME		= DBO.FN_MOM_DATE_DIFF(MFC.TIME, GETDATE())
		, MU.DISPLAY_NAME
		, PICTURE	= ISNULL (MU.PICTURE, '../images/q_silhouette.gif')
		, MFC.MOM_USR_ID
	FROM	#MOM_FRG T
		INNER JOIN MOM_FRG_CMNT MFC (NOLOCK)
		ON	T.ID = MFC.MOM_FRG_ID
		INNER JOIN MOM_USR MU (NOLOCK)
		ON	MFC.MOM_USR_ID = MU.ID
	WHERE	MFC.DELETED = 0

GO