set ANSI_NULLS ON
set QUOTED_IDENTIFIER ON
go


ALTER PROC [dbo].[SP_MOM_RCP_GET_TOPRATED]
AS
BEGIN
	
	SET TRAN ISOLATION LEVEL READ UNCOMMITTED
	SET NOCOUNT ON

	SELECT    ID
			, NAME
			, DESCRIPTION
			, PHOTO = ISNULL (PHOTO, '../images/nopic.jpg')
			, COOK_TM AS COOKINGTIME
			, MOM_USR_ID
			, VIEWS
			, RATING
			, (SELECT FULL_NAME FROM MOM_USR WHERE ID = MOM_USR_ID) AS SUBMITTEDBY
			, (SELECT Count(ID) FROM MOM_RCP_CMT WHERE MOM_RCP_ID = MR.ID) AS COMMENTS
	FROM MOM_RCP MR
	ORDER BY RATING DESC

END



