ALTER PROC SP_MOM_USR_CHECK_BY_EMAIL_ADDR
(
	@EMAIL_ADDR	NVARCHAR (255)
)
AS
	SET TRAN ISOLATION LEVEL READ UNCOMMITTED
	SET NOCOUNT ON 
	
	SELECT	COUNT (1)
	FROM	MOM_USR (NOLOCK)
	WHERE	EMAIL_ADDR = @EMAIL_ADDR

GO