ALTER PROC SP_MOM_QSTN_GET_BY_MOM_CATG_ID
(
	@MOM_CATG_ID	INT = NULL
)
AS
BEGIN TRAN

	DECLARE @MOM_QSTN_ANWS TABLE
	(
		  MOM_QSTN_ID	INT PRIMARY KEY CLUSTERED
		, ANSWERS_COUNT	INT
	)
	
	INSERT INTO @MOM_QSTN_ANWS
	SELECT	  MOM_QSTN_ID
		, ANSWERS_COUNT = COUNT (1)
	FROM	MOM_ANWS (NOLOCK)
	WHERE	ABUSE = 0
	GROUP BY	  MOM_QSTN_ID
	
	SELECT	  Q.ID
		, Q.QUESTION
		, TIME		= DBO.FN_MOM_DATE_DIFF(Q.TIME, GETDATE())
		, Q.MOM_CATG_ID
		, Q.MOM_USR_ID
		, U.DISPLAY_NAME
		, ANSWERS_COUNT	= ISNULL (T.ANSWERS_COUNT, 0)
		, PICTURE	= ISNULL (U.PICTURE, '../images/q_silhouette.gif')
	FROM	MOM_QSTN Q (NOLOCK)
		INNER JOIN MOM_USR U (NOLOCK)
		ON	Q.MOM_USR_ID = U.ID
		LEFT OUTER JOIN @MOM_QSTN_ANWS T
		ON	Q.ID = T.MOM_QSTN_ID
	WHERE	(MOM_CATG_ID = @MOM_CATG_ID OR @MOM_CATG_ID IS NULL)
	AND	ABUSE = 0
	ORDER BY	Q.TIME DESC

COMMIT TRAN