ALTER PROC SP_MOM_ANWS_GET_BY_MOM_QSTN_ID
(
	@MOM_QSTN_ID	INT
)
AS
	SET TRAN ISOLATION LEVEL READ UNCOMMITTED
	SET NOCOUNT ON
	
	SELECT	  A.ANSWER
		, TIME		= DBO.FN_MOM_DATE_DIFF(A.TIME, GETDATE())
		, U.DISPLAY_NAME
		, PICTURE	= ISNULL (U.PICTURE, '../images/q_silhouette.gif')
		, U.ID
	FROM	MOM_ANWS A (NOLOCK)
		INNER JOIN MOM_USR U (NOLOCK)
		ON	A.MOM_USR_ID = U.ID
	WHERE	A.MOM_QSTN_ID = @MOM_QSTN_ID
	AND	A.ABUSE = 0
	ORDER BY	A.TIME DESC
GO