set ANSI_NULLS ON
set QUOTED_IDENTIFIER ON
go

ALTER PROC [dbo].[SP_MOM_USR_GET_BY_NAME]
(
	  @DISPLAY_NAME	NVARCHAR (200)
)
AS
	SET TRAN ISOLATION LEVEL READ UNCOMMITTED
	SET NOCOUNT ON

	SELECT	  ID
		, EMAIL_ADDR
		, PASSWORD
		, FIRST_NAME
		, LAST_NAME
		, FULL_NAME
		, SEX
		, DOB
		, DISPLAY_NAME
		, NEWLETTER
		, TIME
		, LAST_LOGIN_DATE
		, ACTIVE
		, BLOCKED
		, PICTURE = ISNULL (PICTURE, '../images/q_silhouette.gif')
		, PICTURE_STATUS
	FROM	MOM_USR (NOLOCK)
	WHERE	DISPLAY_NAME = @DISPLAY_NAME
	AND	ACTIVE = 1
	AND	BLOCKED = 0


