set ANSI_NULLS ON
set QUOTED_IDENTIFIER ON
go

ALTER PROC [dbo].[SP_MOM_USR_BASICS_UPDATE]
(
	  @COUNTRY		NVARCHAR(50)	= NULL
	, @ZIP			NVARCHAR(10)	= NULL
	, @LOCATION		NVARCHAR(255)	= NULL
	, @MOM_USR_ID	BIGINT
)
AS
	SET TRAN ISOLATION LEVEL READ UNCOMMITTED
	SET NOCOUNT ON
	
	BEGIN TRAN
	
	BEGIN TRY

	UPDATE MOM_USR
	SET		  COUNTRY	= @COUNTRY
			, ZIP		= @ZIP
			, LOCATION	= @LOCATION
	WHERE	ID = @MOM_USR_ID

	END TRY
	BEGIN CATCH
	
		DECLARE @ErrorMessage NVARCHAR(4000);
		DECLARE @ErrorSeverity INT;
		DECLARE @ErrorState INT;
		
		SELECT	  @ErrorMessage = ERROR_MESSAGE()
			, @ErrorSeverity = ERROR_SEVERITY()
			, @ErrorState = ERROR_STATE();
	
		IF @@TRANCOUNT > 0 
			ROLLBACK TRAN
		
		RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);	
	END CATCH
	
	IF @@TRANCOUNT > 0
		COMMIT TRAN


