ALTER PROC SP_MOM_USR_LOGIN
(
	  @EMAIL_ADDR	NVARCHAR (200)
	, @PASSWORD	NVARCHAR (100)
)
AS
BEGIN TRAN

	SELECT	  ID
		, EMAIL_ADDR
		, PASSWORD
		, FIRST_NAME
		, LAST_NAME
		, FULL_NAME
		, SEX
		, DOB
		, DISPLAY_NAME
		, NEWLETTER
		, TIME
		, LAST_LOGIN_DATE
		, ACTIVE
		, BLOCKED
		, PICTURE = ISNULL (PICTURE, '../images/q_silhouette.gif')
		, PICTURE_STATUS
	FROM	MOM_USR (NOLOCK)
	WHERE	EMAIL_ADDR = @EMAIL_ADDR
	AND	PASSWORD = @PASSWORD
	AND	ACTIVE = 1
	AND	BLOCKED = 0

COMMIT TRAN