set ANSI_NULLS ON
set QUOTED_IDENTIFIER ON
go


ALTER PROCEDURE [dbo].[SP_MOM_GET_NEW_MAILS]
	  @MOM_USR_NAME VARCHAR(255) = NULL
	, @MOM_READ		BIT = NULL
AS
BEGIN
	SET TRAN ISOLATION LEVEL READ UNCOMMITTED
	SET NOCOUNT ON;

    SELECT  COUNT(ML.ID) AS NEWMAILS
	FROM	MOM_MAIL ML 
	INNER JOIN	MOM_USR USR ON ML.MOM_USR_ID = USR.ID
	WHERE	MOM_TO_EMAIL LIKE @MOM_USR_NAME
	AND		MOM_READ = @MOM_READ

END




