ALTER PROC SP_MOM_GRP_GET_BY_MOM_USR_ID
(
	@MOM_USR_ID	BIGINT
)
AS
BEGIN

	SET TRAN ISOLATION LEVEL READ UNCOMMITTED
	SET NOCOUNT ON
	
	SELECT	FRND_MOM_USR_ID
	INTO	#MOM_FRND_TEMP
	FROM	MOM_FRND (NOLOCK)
	WHERE	MOM_USR_ID = @MOM_USR_ID
	AND	BLOCKED = 0
	
	UNION
	
	SELECT	MOM_USR_ID
	FROM	MOM_FRND (NOLOCK)
	WHERE	FRND_MOM_USR_ID = @MOM_USR_ID
	AND	BLOCKED = 0
	
	SELECT	*
	FROM	MOM_GRP (NOLOCK)
	WHERE	MOM_USR_ID = @MOM_USR_ID
	AND	BLOCKED = 0
	
	SELECT	  MOM_GRP_ID	= MG.ID
		, MOM_GRP_NAME	= MG.NAME
		, MG.DESCRIPTION
		, MOM_USR_ID	= MU.ID
		, MOM_USR_NAME	= MU.DISPLAY_NAME
		, MG.MEMBERS
	FROM	#MOM_FRND_TEMP T 
		INNER JOIN MOM_GRP_USR MGU (NOLOCK)
		ON	T.FRND_MOM_USR_ID = MGU.MOM_USR_ID
		INNER JOIN MOM_GRP MG (NOLOCK)
		ON	MGU.MOM_GRP_ID = MG.ID
		INNER JOIN MOM_USR MU (NOLOCK)
		ON	MU.ID = MGU.MOM_USR_ID
	WHERE	MGU.BLOCKED	= 0
	AND	MG.BLOCKED	= 0
	AND	DATEDIFF (DD, MGU.TIME, GETDATE()) < 60
	
END