ALTER PROC SP_MOM_FRND_GET_BY_MOM_USR_ID
(
	@MOM_USR_ID	BIGINT
)
AS
	SET TRAN ISOLATION LEVEL READ UNCOMMITTED
	SET NOCOUNT ON
	
	SELECT	  MF.ID
		, MOM_USR_ID	= MF.FRND_MOM_USR_ID
		, PICTURE	= ISNULL (MU.PICTURE, '../images/q_silhouette.gif')
		, MU.DISPLAY_NAME
		, MU.FULL_NAME
	FROM	MOM_FRND MF (NOLOCK)
		INNER JOIN MOM_USR MU (NOLOCK)
		ON	MF.FRND_MOM_USR_ID = MU.ID
	WHERE	MOM_USR_ID	= @MOM_USR_ID

	UNION ALL

	SELECT	  MF.ID
		, MOM_USR_ID	= MF.MOM_USR_ID
		, MU.PICTURE
		, MU.DISPLAY_NAME
		, MU.FULL_NAME
	FROM	MOM_FRND MF (NOLOCK)
		INNER JOIN MOM_USR MU (NOLOCK)
		ON	MF.MOM_USR_ID = MU.ID
	WHERE	FRND_MOM_USR_ID	= @MOM_USR_ID
GO