set ANSI_NULLS ON
set QUOTED_IDENTIFIER ON
go


ALTER PROC [dbo].[SP_MOM_KIDS_ADD]
(
	  @KID_FIRST_NAME	VARCHAR (50)
	, @KID_GENDER		VARCHAR (20)
	, @KID_DOB			DATETIME		= NULL
	, @KID_ABOUT		VARCHAR (100) 	= NULL
	, @KID_PHOTO		VARCHAR (100) 	= NULL
	, @MOM_USR_ID		BIGINT
)
AS
	SET TRAN ISOLATION LEVEL READ UNCOMMITTED
	SET NOCOUNT ON
	
	BEGIN TRAN
	
	BEGIN TRY

	INSERT INTO MOM_KIDS
	(
		  KID_FIRST_NAME
		, KID_GENDER
		, KID_DOB
		, KID_ABOUT
		, KID_PHOTO
		, MOM_USR_ID
	)
	VALUES
	(
		  @KID_FIRST_NAME
		, @KID_GENDER
		, @KID_DOB
		, @KID_ABOUT
		, @KID_PHOTO
		, @MOM_USR_ID
	)

	END TRY
	BEGIN CATCH
	
		DECLARE @ErrorMessage NVARCHAR(4000);
		DECLARE @ErrorSeverity INT;
		DECLARE @ErrorState INT;
		
		SELECT	  @ErrorMessage = ERROR_MESSAGE()
			, @ErrorSeverity = ERROR_SEVERITY()
			, @ErrorState = ERROR_STATE();
	
		IF @@TRANCOUNT > 0 
			ROLLBACK TRAN
		
		RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);	
	END CATCH
	
	IF @@TRANCOUNT > 0
		COMMIT TRAN

