ALTER PROC SP_MOM_QSTN_ADD
(
	  @MOM_USR_ID	BIGINT
	, @MOM_CATG_ID	INT
	, @QUESTION	NVARCHAR (100)
	, @DESCRIPTION	NVARCHAR (2000)
	, @EMAIL_STATUS	BIT
)
AS
	SET TRAN ISOLATION LEVEL READ UNCOMMITTED
	SET NOCOUNT ON
	
	BEGIN TRAN
	
	BEGIN TRY	
		

			INSERT INTO MOM_QSTN
			(
				  MOM_USR_ID
				, MOM_CATG_ID
				, QUESTION
				, DESCRIPTION
				, EMAIL_STATUS
			)
			VALUES
			(
				  @MOM_USR_ID
				, @MOM_CATG_ID
				, @QUESTION
				, @DESCRIPTION
				, @EMAIL_STATUS
			)
		
	END TRY
	BEGIN CATCH
	
		DECLARE @ErrorMessage NVARCHAR(4000);
		DECLARE @ErrorSeverity INT;
		DECLARE @ErrorState INT;
		
		SELECT	  @ErrorMessage = ERROR_MESSAGE()
			, @ErrorSeverity = ERROR_SEVERITY()
			, @ErrorState = ERROR_STATE();
	
		IF @@TRANCOUNT > 0 
			ROLLBACK TRAN
		
		RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);	
	END CATCH
	
	IF @@TRANCOUNT > 0
		COMMIT TRAN
GO