ALTER PROC SP_MOM_FRG_ADD
(
	  @MOM_USR_ID	BIGINT
	, @SHARE		NVARCHAR (255)
	, @TYPE		CHAR (1) = 'D'
	, @TYPE_SHARE	NVARCHAR (4000) = NULL
)
AS
	SET TRAN ISOLATION LEVEL READ UNCOMMITTED
	SET NOCOUNT ON
	
	BEGIN TRAN
		
	BEGIN TRY	
		

		DECLARE @MOM_FRG_ROW TABLE
		(
			  ID		INT
			, MOM_USR_ID	BIGINT
			, SHARE		NVARCHAR (255)
			, TYPE		CHAR (1)
			, TYPE_SHARE	NVARCHAR (4000)
		)

		INSERT INTO MOM_FRG
		(
			  MOM_USR_ID
			, SHARE
		)
		OUTPUT	  INSERTED.ID
			, INSERTED.MOM_USR_ID
			, INSERTED.SHARE
			, INSERTED.TYPE
			, INSERTED.TYPE_SHARE
		INTO	@MOM_FRG_ROW
		VALUES
		(
			  @MOM_USR_ID
			, @SHARE
		)
		
		SELECT	*
		FROM	@MOM_FRG_ROW

		
	END TRY
	BEGIN CATCH
	
		DECLARE @ErrorMessage NVARCHAR(4000);
		DECLARE @ErrorSeverity INT;
		DECLARE @ErrorState INT;
		
		SELECT	  @ErrorMessage = ERROR_MESSAGE()
			, @ErrorSeverity = ERROR_SEVERITY()
			, @ErrorState = ERROR_STATE();
	
		IF @@TRANCOUNT > 0 
			ROLLBACK TRAN
		
		RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);	
	END CATCH
	
	IF @@TRANCOUNT > 0
		COMMIT TRAN
GO