IF OBJECT_ID('SP_MOM_FRG_ADD') IS NOT NULL
	DROP PROC SP_MOM_FRG_ADD
GO
CREATE PROC SP_MOM_FRG_ADD
(
	  @MOM_USR_ID	BIGINT
	, @SHARE		NVARCHAR (255)
)
AS
BEGIN TRAN

	DECLARE @MOM_FRG_ROW TABLE
	(
		  ID		INT
		, MOM_USR_ID	BIGINT
		, SHARE		NVARCHAR (255)
		, TIME		DATETIME
	)

	INSERT INTO MOM_FRG
	(
		  MOM_USR_ID
		, SHARE
	)
	OUTPUT	  INSERTED.ID
		, INSERTED.MOM_USR_ID
		, INSERTED.SHARE
		, INSERTED.TIME
	INTO	@MOM_FRG_ROW
	VALUES
	(
		  @MOM_USR_ID
		, @SHARE
	)
	
	SELECT	  ID
		, MOM_USR_ID
		, SHARE
		, TIME	= DBO.FN_MOM_DATE_DIFF(TIME, GETDATE())
	FROM	@MOM_FRG_ROW

COMMIT TRAN