set ANSI_NULLS ON
set QUOTED_IDENTIFIER ON
go

ALTER PROCEDURE [dbo].[SP_MOM_TAGS_GET_BY_NAMESPACE]
	  @NAMESPACE VARCHAR(50) = NULL
AS
BEGIN
	SET TRAN ISOLATION LEVEL READ UNCOMMITTED
	SET NOCOUNT ON;

    SELECT  
			  ID
			, TAG
			, MOM_ID
			, (SELECT COUNT(*) FROM MOM_TAGS T2 WHERE T2.TAG = T1.TAG) TAG_COUNT
	FROM MOM_TAGS T1 
	WHERE NAMESPACE = @NAMESPACE
	ORDER BY TAG_COUNT

END



