IF OBJECT_ID('SP_MOM_FRG_CMNT_ADD') IS NOT NULL
	DROP PROC SP_MOM_FRG_CMNT_ADD
GO
CREATE PROC SP_MOM_FRG_CMNT_ADD
(
	  @MOM_FRG_ID	INT
	, @MOM_USR_ID	BIGINT
	, @COMMENTS	NVARCHAR (255)
)
AS
BEGIN TRAN

	INSERT INTO MOM_FRG_CMNT
	(
		  MOM_FRG_ID
		, MOM_USR_ID
		, COMMENTS
	)
	VALUES
	(
		  @MOM_FRG_ID
		, @MOM_USR_ID
		, @COMMENTS
	)

COMMIT TRAN