CREATE PROCEDURE SP_MOM_BLG_GET
AS
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	SET NOCOUNT ON

	SELECT	  MB.ID
		, MB.TITLE
		, MB.BLOG
		, TIME		= DBO.FN_MOM_DATE_DIFF(MB.TIME, GETDATE())
		, MB.RATE
		, MOM_USR_ID	= MU.ID
		, MU.DISPLAY_NAME
	FROM	MOM_BLG MB (NOLOCK)
		INNER JOIN MOM_USR MU (NOLOCK)
		ON	MB.MOM_USR_ID = MU.ID
	WHERE	MB.ABUSE = 0
	AND	MU.BLOCKED = 0
GO