ALTER PROC SP_MOM_QSTN_MOM_ANWS_GET_BY_MOM_QSTN_ID
(
	@ID	INT
)
AS
	SET TRAN ISOLATION LEVEL READ UNCOMMITTED
	SET NOCOUNT ON
	
	SELECT	  Q.ID
		, Q.QUESTION
		, Q.DESCRIPTION
		, U.DISPLAY_NAME
	FROM	MOM_QSTN Q
		INNER JOIN MOM_USR U
		ON	Q.MOM_USR_ID = U.ID
	WHERE	Q.ID = @ID
	
	SELECT	  A.ANSWER
		, TIME		= DBO.FN_MOM_DATE_DIFF(A.TIME, GETDATE())
		, U.DISPLAY_NAME
		, PICTURE	= ISNULL (U.PICTURE, '../images/q_silhouette.gif')
		, U.ID
	FROM	MOM_ANWS A (NOLOCK)
		INNER JOIN MOM_USR U (NOLOCK)
		ON	A.MOM_USR_ID = U.ID
	WHERE	A.MOM_QSTN_ID = @ID
	AND	A.ABUSE = 0
	ORDER BY	A.TIME DESC
	
GO